services:
  mongo_db:
    image: mongo:4.2
    restart: always
    container_name: guitar_shop_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    ports:
      - ${MONGO_DB_PORT}:27017
    volumes:
      - guitar_shop_mongo_data:/data/db
    healthcheck:
        test: echo 'db.runCommand("ping").ok' | mongosh localhost:27019/guitar-shop-db --quiet
        interval: 10s
        timeout: 10s
        retries: 5

  mongo_db_ui:
    image: mongo-express:1.0.2-20
    restart: always
    container_name: guitar_shop_mongo_express
    ports:
      - 8087:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_DB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_DB_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@mongo_db:27017/


  postgres_db:
    image: postgres:14-alpine
    container_name: guitar_shop_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes:
      - guitar_shop_postgres_data:/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - guitar_shop_network

  postgres_db_ui:
    image: dpage/pgadmin4
    container_name: guitar_shop_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 8085:80
    depends_on:
      - postgres_db
    networks:
      - guitar_shop_network

networks:
  guitar_shop_network:
      driver: bridge

volumes:
  guitar_shop_mongo_data:
  guitar_shop_postgres_data:
